coursenotes/urls.py
from django.conf.urls import url
from . import views

app_name = 'coursenotes'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<course_slug>[\w-]+)/$', views.course_index, name='course_index'),
    url(r'^(?P<course_slug>[\w-]+)/ch/(?P<ch_num>[0-9]+)/$', views.chapter_view, name='chapter_view'),
    url(r'^(?P<course_slug>[\w-]+)/info/$', views.course_info_page, name='course_info')
]

finance/urls.py
from django.conf.urls import url
from . import views

app_name = 'finance'

urlpatterns = [
    url(r'^$', views.basic_view, name='basic_view'),
    url(r'^edit/([0-9]+)/$', views.populated_basic_view, name='populated_basic_view'),
    url(r'^submitchangestable/$', views.sumbit_changes_in_table, name='sumbit_changes_table'),
    url(r'^submittransactionform/$', views.submit_transaction_form, name='submit_transaction_form')
]

personalSite/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^finance/', include('finance.urls')),
    url(r'^notes/', include('coursenotes.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

coursenotes/models.py
from django.db import models
from django.utils.text import slugify
import markdown
import pypandoc

class Course(models.Model):
    """
    Represents a course that has been taken.

    Attributes:
        name - The given name of the course.
        dept_num - The 4 digit code that corresponds to the department which offers
                   the course.
        course_num - The corresponding course number of the course.
        year - The year the course was taken. 1 for first year, 2 for second year, ...
        semester - The semester in which the course was taken. 1 for fall, 2 for
                   spring, 3 for summer. Preferably, use the provided constants:
                   SEM_FALL, SEM_SPRING, SEM_SUMMER.
        instructor - Person who taught the class.
    """
    name = models.CharField(max_length=500)
    dept_num = models.CharField(max_length=4)
    course_num = models.CharField(max_length=50)
    year = models.SmallIntegerField()
    semester = models.SmallIntegerField()
    instructor = models.CharField(max_length=1000)
    slug = models.SlugField(unique=True)

    SEM_FALL = 1
    SEM_SPRING = 2
    SEM_SUMMER = 3

    def semester_name(self):
        """
        Returns the string name of the objects semester. Throwns and error if the
        semester is not one of SEM_FALL, SEM_SPRING, SEM_SUMMER.
        """
        if (self.semester == self.SEM_FALL):
            return "Fall"
        if (self.semester == self.SEM_SPRING):
            return "Spring"
        if (self.semester == self.SEM_SUMMER):
            return "Summer"


    def generate_slug(self):
        """
        Generates a unique slug for the object does **not** save the object. If a
        course already exists with that same slug, it should append a unque slug
        modifer to the end of the slug that is 1 more than the largest modifer already
        in existance.

        Ex.
            If CSCI-2011 and CSCI-2011-2 and CSCI-2011-4 already exist, then the unique
            slug generated will be CSCI-2011-5.

        Assumes that all slugs share the same structure:
            <dept>-<course_num>   OR   <dept>-<course_num>-<slug_unique_modifier>
        where the unique slug modifier is a positive integer. This is important because
        this is expolited when generating a unique slug.
        """
        new_slug = slugify(self.dept_num) + '-' + slugify(self.course_num)

        # Ensure uniqueness.
        similar_slugs = [course.slug for course in Course.objects.filter(slug__startswith=new_slug).all()]
        slug_modifiers = [slug.split(new_slug)[1][1:] for slug in similar_slugs]
        # Repalce blank with 0 and cast other modifers to int.
        slug_modifiers = [1 if modifier == '' else int(modifier) for modifier in slug_modifiers]

        if len(slug_modifiers) <= 0:
            return new_slug
        else:
            return new_slug + '-' + str(max(slug_modifiers)+1)


    def save(self, *args, **kwargs):
        if self.slug == None or self.slug == '':
            self.slug = self.generate_slug()
        super(Course, self).save(*args, **kwargs)


    def __str__(self):
        return self.name



class TextBook(models.Model):
    """
    Represents a text book that was used in a course.

    Attributes:
        title
        course - The course for which the book was used.
    """
    title = models.CharField(max_length=1000)
    course = models.ForeignKey('Course', on_delete=models.CASCADE)

    def __str__(self):
        return self.title



class Author(models.Model):
    """
    Represents a single author of a TextBook, a book can have multiple authors.

    Attributes:
        name
        book - The TextBook to which the author is assosiated.
    """
    name = models.CharField(max_length=1000)
    book = models.ForeignKey('Textbook', on_delete=models.CASCADE)

    def __str__(self):
        return self.name




class Chapter(models.Model):
    """
    Represents a chapter that was covered in a TextBook.

    Attributes:
        parent_book - The TextBook to which the chapter is assosiated.
        number - The number of the chapter.
        title - The chapter's title.
    """
    course = models.ForeignKey('Course', on_delete=models.CASCADE)
    number = models.SmallIntegerField()
    title = models.CharField(max_length=500)

    def __str__(self):
        return self.title



class Section(models.Model):
    """
    Represents a section within a Chapter of a TextBook.

    Attributes:
        parent_chapter - The Chapter to which the section belongs.
        number - The section's number.
        title - The *optional* title of the section.
        content_markdown - The markdown that is the section's notes. This should be
                           the only thing that the user ever edits.
        content_html - The safe html that is generated from the user-defined
                       content_markdown.
    """
    parent_chapter = models.ForeignKey('Chapter', on_delete=models.CASCADE)
    number = models.SmallIntegerField()
    title = models.CharField(max_length=500, blank=True)
    content_markdown = models.TextField()
    content_html = models.TextField()

    GRAPH_START_TAG = '<graph>'
    GRAPH_END_TAG = '</graph>'

    def get_markdown_with_image_refs(self, markdown):
        """
        Returns a string of markdown with image urls appended to end.

        Argument 'markdown' is not modified.

        Takes advantatge of the syntax in markdown to append the urls of named images
        at the end of a file in order to make inclusion of images easier.
        """
        image_refs = ""

        for image in self.sectionimage_set.all():
            image_refs += '\n[{0}]: {1}'.format(image.name, image.image.url)

        return '{0}\n{1}'.format(markdown, image_refs) # Append image_refs to markdown.

    def get_markdown_graphviz_sub(self, markdown):
        """
        Substitutes graphviz start and end tags with appropriate, working tags and
        returns result.

        Argument 'markdown' is not modified.
        """
        working_start_tag = "<img src='http://g.gravizo.com/g?"
        working_end_tag = "'/>"

        copy = markdown.replace(self.GRAPH_START_TAG, working_start_tag)
        copy = copy.replace(self.GRAPH_END_TAG, working_end_tag)

        return copy

    def save(self):

        processed_markdown = self.get_markdown_with_image_refs(self.content_markdown)
        processed_markdown = self.get_markdown_graphviz_sub(processed_markdown)

        self.content_html = pypandoc.convert(processed_markdown, format='md',
                    to='html', extra_args=['--mathjax'])

        super(Section, self).save()

    def __str__(self):
        return self.title


class SectionImage(models.Model):
    name = models.CharField(max_length=250)
    image = models.ImageField(upload_to="notes/images")
    parent = models.ForeignKey('Section', on_delete=models.CASCADE)

coursenotes/views.py
from .models import Author, Chapter, Course, TextBook
from collections import OrderedDict
from django.db.models import Max
from django.shortcuts import render



def get_base_context():
    max_year = Course.objects.all().aggregate(Max('year'))['year__max']
    max_sem = Course.objects.filter(year=max_year).aggregate(Max('semester'))['semester__max']
    latest_course = Course.objects.order_by('-year', '-semester')[0]
    return {
        'recent_courses': Course.objects.filter(year=latest_course.year, semester=latest_course.semester).order_by('course_num')
    }



def index(request):
    courses_by_sem = OrderedDict()
    for course in Course.objects.order_by('-year', '-semester', 'course_num'):
        when_taken = "{0} Year {1}".format(course.semester_name(), course.year)
        if when_taken in courses_by_sem:
            courses_by_sem[when_taken].append(course)
        else:
            courses_by_sem[when_taken] = [course, ]

    context = {
        'courses_by_sem': courses_by_sem,
    }
    context.update(get_base_context())
    return render(request, 'coursenotes/index.html', context)



def course_index(request, course_slug):
    context = {
        'course': Course.objects.get(slug=course_slug),
    }
    context.update(get_base_context())
    return render(request, 'coursenotes/course_index.html', context)



def chapter_view(request, course_slug, ch_num):
    context = {
        'ch': Course.objects.get(slug=course_slug).chapter_set.get(number=ch_num),
    }
    context.update(get_base_context())
    return render(request, 'coursenotes/chapter_view.html', context)



def course_info_page(request, course_slug):
    context = {
        'course': Course.objects.get(slug=course_slug),
    }
    context.update(get_base_context())
    return render(request, 'coursenotes/course_info.html', context)

coursenotes/templates/coursenotes/base.html
{% load custom_tags %}

<!DOCTYPE html>
<html>



<head>
    <!-- Properites -->
    <title>All Notes</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>

    <!-- Bootstrap stuff -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <!-- Cusom stuff -->
    <script type="text/javascript">
        $(document).ready(function(){

            // Load notes homepage on double click of the notes dropdown.
            $('#nav-notes-dropdown').dblclick(function(e){
                var url = $(this).attr('data-target-url');
                console.log('hi there');
                window.location.href = url;
            });

        });
    </script>
    {% block additional_resources %}{% endblock %}
</head>



<body>

    <!-- Navbar -->
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">

            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-navbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#" >Kris Swann</a>
            </div>

            <div class="collapse navbar-collapse" id="main-navbar">

                <ul class="nav navbar-nav">
                    <li class="dropdown">

                        <a id="nav-notes-dropdown" class="dropdown-toggle" data-toggle="dropdown" data-target-url="{% url 'coursenotes:index' %}">
                            Notes <span class="caret"></span>
                        </a>

                        <ul class="dropdown-menu">
                            <li class="dropdown-header">Latest courses</li>
                            {% for course in recent_courses %}
                            <li class="{% route_active request 'coursenotes:course_index' course.slug %}">
                                <a href="{% url 'coursenotes:course_index' course.slug %}">{{ course.dept_num }} {{ course.course_num }} - <small>{{ course.name }}</small></a>
                            </li>
                            {% endfor %}

                            <li role="separator" class="divider"></li>

                            <li class="{% route_active request 'coursenotes:index' %}">
                                <a href="{% url 'coursenotes:index' %}">All courses</a>
                            </li>
                        </ul>

                    </li>
                </ul>

                <p class="navbar-text navbar-right hidden-xs">Uninspired slag.</p>

            </div>

        </div>
    </nav>



    {% block body %}{% endblock %}

</body>



</html>

coursenotes/templates/coursenotes/chapter_view.html
{% extends "coursenotes/base.html" %}
{% load staticfiles %}



{% block additional_resources %}
<script src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>

<script type="text/javascript">
    $(document).ready(function(){
        $(".panel-heading").click(function(e){
            var sec = $(this).attr("sec-num");
            $("#sec-" + sec).collapse("toggle");
        });
    });
</script>
{% endblock %}



{% block body %}
<div class="container">

    <div class="page-header">
        <h1>
            {% if user.is_superuser %}
            <a href="{% url 'admin:coursenotes_chapter_change' ch.id %}" class="btn btn-link btn-lg pull-right">
                <span class="glyphicon glyphicon-edit"></span> <span class="hidden-xs">Edit me!</span>
            </a>
            {% endif %}
            Ch {{ ch.number }}. {{ ch.title }}
        </h1>
    </div>



    <div class="panel-group">
        {% for section in ch.section_set.all %}
        <div class="panel panel-primary">

            <div class="panel-heading" sec-num="{{ section.number }}">
                <h3 class="panel-title">{{ ch.number }}.{{ section.number }} {{ section.title }}</h1>
            </div>

            <div id="sec-{{ section.number }}" class="panel-collapse collapse in">
                <div class="panel-body">
                    {{ section.content_html|safe }}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

</div>
{% endblock %}

coursenotes/templates/coursenotes/course_index.html
{% extends "coursenotes/base.html" %}
{% load staticfiles %}
{% load custom_tags %}



{% block additional_resources %}
<script type="text/javascript">
    $(document).ready(function(){

        // Toggle collapse of section lists.
        $(".panel-heading").click(function(e){
            console.log("foo");
            var ch = $(this).attr("ch-num");
            $("#sec-list-ch" + ch).collapse("toggle");
        });

        // Keep panel from collapsing (toggling) when clicking on link.
        // Makes the state remain the same when using the back button in browser.
        $(".panel-heading a").click(function(e){
            e.stopPropagation();
        });
    });
</script>
{% endblock %}



{% block body %}
<div class="container">

    <div class="row">
        <div class="col-xs-11">
            <h1>{{ course.dept_num }} {{ course.course_num }} <small>{{ course.name }}</small></h1>
        </div>
        <div class="col-xs-1">
            <h3>
                <a href="{% url 'coursenotes:course_info' course.slug %}">
                    <span class="glyphicon glyphicon-info-sign"></span>
                </a>
            </h3>
        </div>
    </div>



    <div class="panel-group">

        {% for ch in course.chapter_set.all %}
        <div class="panel panel-default">

            <div class="panel-heading" ch-num="{{ ch.number }}">
                {% if user.is_superuser %}
                <a href="{% url 'admin:coursenotes_chapter_change' ch.id %}" class="pull-right">
                    <span class="glyphicon glyphicon-edit"></span>
                </a>
                {% endif %}
                <a href="{% url 'coursenotes:chapter_view' course.slug ch.number %}">{{ ch.number }}. {{ ch.title }}</a>
            </div>

            <div id="sec-list-ch{{ ch.number }}" class="panel-collapse collapse">
                <ul class="list-group">
                {% for sec in ch.section_set.all %}
                    <li class="list-group-item text-muted"><small>{{ sec.number }}. {{ sec.title }}</small></li>
                {% endfor %}
                </ul>
            </div>

        </div>
        {% endfor %}



        <!-- Add new chapter -->
        {% if user.is_superuser %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <a href="{% url_with_query 'admin:coursenotes_chapter_add' course=course.id %}">
                    <span class="glyphicon glyphicon-plus"></span> Add another chapter
                </a>
            </div>
        </div>
        {% endif %}

    </div>

</div>
{% endblock %}

coursenotes/templates/coursenotes/course_info.html
{% extends "coursenotes/base.html" %}
{% load humanize %}
{% load staticfiles %}



{% block body %}
<div class="container">

    <h1 class="text-primary">Info about...</h1>



    <h1>{{ course.dept_num }} {{ course.course_num }} <small>{{ course.name }}</small></h1>



    <div class="panel panel-default">
        <div class="panel-heading">Taken...</div>
        <div class="panel-body">{{ course.semester_name }} of my {{ course.year|ordinal }} Year</div>
    </div>



    <div class="panel panel-default">
        <div class="panel-heading">Instructor(s)</div>
        <div class="panel-body">{{ course.instructor }}</div>
    </div>



    <div class="panel panel-default">
        <div class="panel-heading">Textbook(s)</div>
        <div class="panel-body">
            {% for text in course.textbook_set.all %}
            <p><strong>{{ text.title }}</strong> <small>by {% for author in text.author_set.all %}{{ author.name }} {% endfor %}</small></p>
            {% endfor %}
        </div>
    </div>

</div>
{% endblock %}

coursenotes/templates/coursenotes/index.html
{% extends "coursenotes/base.html" %}
{% load staticfiles %}



{% block body %}
<div class="container">

    <h1>Course notes</h1>



    <h4 class="text-muted">For the courses I have taken at the University of Minnesota -- Twin Cities.</h4>



    {% for when_taken, courses in courses_by_sem.items %}
    <div class="panel panel-default">

        <div class="panel-heading">
            <h3 class="panel-title">{{ when_taken }}</h3>
        </div>



        <div class="panel-body">
            {% for course in courses %}
            <div class="row">
                <div class="col-xs-11">
                    <a href="{% url 'coursenotes:course_index' course.slug %}">
                        {{ course.dept_num }} {{ course.course_num }} - {{ course.name }}
                    </a>
                </div>
                <div class="col-xs-1">
                    <a href="{% url 'coursenotes:course_info' course.slug %}">
                        <span class="glyphicon glyphicon-info-sign"></span>
                    </a>
                </div>
            </div>
            {% endfor %}
        </div>

    </div>
    {% endfor %}

</div>
{% endblock %}